// Package id generates the application-side identifiers Holler uses
// everywhere: UUIDv7, time-sortable, generated by the application and never by
// the database (§74, ADR-011). Sequential primary keys are never exposed as
// security identifiers.
package id

import "github.com/google/uuid"

// New returns a fresh UUIDv7 string. It panics only if the system entropy
// source fails, which is not a recoverable condition for a request path.
func New() string {
	v, err := uuid.NewV7()
	if err != nil {
		panic("id: uuid v7 generation failed: " + err.Error())
	}
	return v.String()
}

// Parse validates an externally supplied identifier. Callers must use this
// rather than string-comparing raw input.
func Parse(s string) (string, error) {
	v, err := uuid.Parse(s)
	if err != nil {
		return "", err
	}
	return v.String(), nil
}
