// Command devseed prepares a local development database: it applies the
// frozen contract migrations to Postgres, then seeds the shared catalogue
// (tenant, brand, outlet, menu, inventory, recipes, suppliers, a goods
// receipt) from seed/demo-outlet.json -- the single seed source described in
// seed/README.md -- and finally the cloud-only identity rows (role,
// app_user, user_role) that have no SQLite equivalent.
//
// DEVELOPMENT ONLY. This never runs at an outlet and is not part of the
// shipped POS. See docs/DEV_SETUP.md.
//
// It exists because cmd/api is still the Milestone 0 health-only entrypoint
// and never calls postgres.Migrate, so nothing else applies the contract
// schema to a developer's Docker Postgres.
//
// The entity ids below are fixed rather than freshly minted so that a re-run
// is idempotent and so the edge seeder (edge/database, bin devseed) can refer
// to the same outlet/device/user without a handshake. They are real UUIDv7
// values reserved for development; production ids are minted per §74.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/holler/backend/internal/platform/crypto"
	"github.com/holler/backend/internal/platform/postgres"
)

// Fixed development ids. tenantID/outletID are validated against
// seed/demo-outlet.json at load time (seedfile.go, seedFile.validate) rather
// than hand-mirrored by comment -- see seed/README.md. The catalogue rows
// that used to be hand-mirrored here (menu items, variants, modifiers,
// inventory items) are now read from that file; only the cloud-only identity
// rows below (role, app_user, user_role) stay hand-written, because there is
// no role table in SQLite at all (contracts 0.6.0).
const (
	tenantID   = "0191a000-0000-7000-8000-000000000001"
	brandID    = "0191a000-0000-7000-8000-000000000002"
	outletID   = "0191a000-0000-7000-8000-00000000000a"
	deviceID   = "0191a000-0000-7000-8000-00000000000b"
	cashierID  = "0191a000-0000-7000-8000-00000000000c"
	roleID     = "0191a000-0000-7000-8000-00000000000d"
	userRoleID = "0191a000-0000-7000-8000-00000000000e"

	// M5 criterion 5. TWO approval ceilings are required, not one: the
	// refusal must name who CAN approve instead (section 64), and
	// RolesAbleToApprove finds that by looking for a role whose
	// po_approval_limit_paise covers the order total. With a single role
	// seeded, the refusal is correct and names nobody, which is the half of
	// the message that tells the caller what to do next.
	//
	// The buyer holds procurement.approve with the LOW ceiling and is the
	// caller that gets refused. The owner role carries the HIGH ceiling and
	// deliberately has no user: RolesAbleToApprove selects role rows, so a
	// role with no holder is enough to make the message name it, and seeding
	// a second login nobody uses would be fixture noise.
	buyerRoleID     = "0191a000-0000-7000-8000-000000000020"
	ownerRoleID     = "0191a000-0000-7000-8000-000000000021"
	buyerID         = "0191a000-0000-7000-8000-000000000022"
	buyerUserRoleID = "0191a000-0000-7000-8000-000000000023"
	ownerID         = "0191a000-0000-7000-8000-000000000024"
	ownerUserRoleID = "0191a000-0000-7000-8000-000000000025"

	ownerEmail = "owner@holler.test"

	buyerEmail = "buyer@holler.test"

	// 50,000.00 and 500,000.00 rupees, in paise. Criterion 5 raises an order
	// between the two, so the same order is over the buyer's ceiling and
	// under the owner's.
	buyerApprovalLimitPaise = 5_000_000
	ownerApprovalLimitPaise = 50_000_000
)

const (
	cashierEmail = "cashier@holler.test"
	// Development credential only; never a default anywhere else.
	cashierPassword = "holler123"
)

func main() {
	databaseURL := flag.String("database-url", envOr("DATABASE_URL",
		"postgres://holler:holler_dev@localhost:5432/holler?sslmode=disable"),
		"PostgreSQL connection string")
	contractsDir := flag.String("contracts", "../packages/contracts/postgres",
		"directory holding the frozen Postgres migrations")
	seedFilePath := flag.String("seed-file", "../seed/demo-outlet.json",
		"path to the shared seed source (seed/README.md); generated by edge/database/src/bin/devseed.rs --emit-json, never hand-edited")
	flag.Parse()

	ctx := context.Background()

	sf, err := loadSeedFile(*seedFilePath)
	if err != nil {
		log.Fatalf("devseed: %v", err)
	}
	log.Printf("devseed: loaded seed file %s (schema_version %d, generated_by %s)",
		*seedFilePath, sf.SchemaVersion, sf.GeneratedBy)

	pool, err := postgres.Open(ctx, *databaseURL)
	if err != nil {
		log.Fatalf("devseed: %v", err)
	}
	defer pool.Close()

	if err := postgres.Migrate(ctx, pool, *contractsDir); err != nil {
		log.Fatalf("devseed: %v", err)
	}
	log.Printf("devseed: migrations applied from %s", *contractsDir)

	if err := seedCatalogueFromFile(ctx, pool, sf); err != nil {
		log.Fatalf("devseed: %v", err)
	}
	log.Printf("devseed: seeded catalogue from %s", *seedFilePath)

	// One hash, generated here, used by both Postgres and the edge SQLite.
	// password.go is the single implementation of this format (ADR-011) and
	// edge/database/src/auth.rs verifies exactly what it produces.
	hash, err := crypto.HashPassword(cashierPassword)
	if err != nil {
		log.Fatalf("devseed: hashing password: %v", err)
	}

	if err := seed(ctx, pool, hash); err != nil {
		log.Fatalf("devseed: %v", err)
	}
	log.Printf("devseed: seeded role/app_user/user_role")

	// Runs after seed(), not inside seedCatalogueFromFile: the goods receipt
	// and opening-stock ledger rows reference app_user (received_by_user_id /
	// created_by_user_id), which seed() is what creates.
	if err := seedGoodsReceiptAndOpeningStock(ctx, pool, sf); err != nil {
		log.Fatalf("devseed: %v", err)
	}
	log.Printf("devseed: seeded goods receipt and opening stock")

	// Machine-readable block: scripts/dev-bootstrap.ps1 parses these lines.
	// The hash is printed because the edge seeder needs the identical string;
	// it is a hash, not a credential, and this is a development-only path.
	fmt.Println("---HOLLER-DEVSEED---")
	fmt.Printf("HOLLER_TENANT_ID=%s\n", tenantID)
	fmt.Printf("HOLLER_OUTLET_ID=%s\n", outletID)
	fmt.Printf("HOLLER_DEVICE_ID=%s\n", deviceID)
	fmt.Printf("HOLLER_USER_ID=%s\n", cashierID)
	fmt.Printf("HOLLER_SEED_EMAIL=%s\n", cashierEmail)
	fmt.Printf("HOLLER_SEED_PASSWORD=%s\n", cashierPassword)
	fmt.Printf("HOLLER_SEED_PASSWORD_HASH=%s\n", hash)
	fmt.Println("---END---")
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// seed writes the Milestone 1 fixture rows. Every statement is an upsert so
// the command can be re-run against an already-seeded database.
func seed(ctx context.Context, pool postgres.Pool, passwordHash string) error {
	now := time.Now().UTC()

	stmts := []struct {
		label string
		sql   string
		args  []any
	}{
		// tenant/brand/outlet and the whole catalogue (menu, inventory,
		// recipes, suppliers) are seeded by seedCatalogueFromFile, from
		// seed/demo-outlet.json, before this function runs. Only the
		// cloud-only identity rows stay here.
		{"role", `INSERT INTO role (id, tenant_id, code, name, created_at, updated_at)
			VALUES ($1, $2, 'CASHIER', 'Cashier', $3, $3)
			ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = EXCLUDED.updated_at`,
			[]any{roleID, tenantID, now}},

		{"role buyer", `INSERT INTO role
			(id, tenant_id, code, name, po_approval_limit_paise, created_at, updated_at)
			VALUES ($1, $2, 'BUYER', 'Buyer', $3, $4, $4)
			ON CONFLICT (id) DO UPDATE SET
				name = EXCLUDED.name,
				po_approval_limit_paise = EXCLUDED.po_approval_limit_paise,
				updated_at = EXCLUDED.updated_at`,
			[]any{buyerRoleID, tenantID, int64(buyerApprovalLimitPaise), now}},

		{"role owner", `INSERT INTO role
			(id, tenant_id, code, name, po_approval_limit_paise, created_at, updated_at)
			VALUES ($1, $2, 'OWNER', 'Owner', $3, $4, $4)
			ON CONFLICT (id) DO UPDATE SET
				name = EXCLUDED.name,
				po_approval_limit_paise = EXCLUDED.po_approval_limit_paise,
				updated_at = EXCLUDED.updated_at`,
			[]any{ownerRoleID, tenantID, int64(ownerApprovalLimitPaise), now}},

		{"app_user buyer", `INSERT INTO app_user
			(id, tenant_id, email, full_name, password_hash, is_active, config_version, created_at, updated_at)
			VALUES ($1, $2, $3, $4, $5, TRUE, 1, $6, $6)
			ON CONFLICT (id) DO UPDATE SET
				password_hash = EXCLUDED.password_hash,
				is_active = EXCLUDED.is_active,
				updated_at = EXCLUDED.updated_at`,
			[]any{buyerID, tenantID, buyerEmail, "Dev Buyer", passwordHash, now}},

		{"app_user", `INSERT INTO app_user
			(id, tenant_id, email, full_name, password_hash, is_active, config_version, created_at, updated_at)
			VALUES ($1, $2, $3, $4, $5, TRUE, 1, $6, $6)
			ON CONFLICT (id) DO UPDATE SET
				password_hash = EXCLUDED.password_hash,
				is_active = EXCLUDED.is_active,
				updated_at = EXCLUDED.updated_at`,
			[]any{cashierID, tenantID, cashierEmail, "Dev Cashier", passwordHash, now}},
	}

	for _, s := range stmts {
		if _, err := pool.Exec(ctx, s.sql, s.args...); err != nil {
			return fmt.Errorf("seeding %s: %w", s.label, err)
		}
	}

	// role_permission is a composite-key table with no single id to conflict on.
	// inventory.manage / inventory.count are here so the dev principal can
	// reach the M4 surfaces (current stock, counts, wastage, the
	// items-sold-with-no-recipe report). Keep this list identical to
	// CASHIER_PERMISSIONS in edge/database/src/bin/devseed.rs — the edge
	// stores the flattened list and a config pull replaces, not merges.
	//
	// procurement.manage (M5) gates the receiving and purchase-return surfaces
	// on the POS (apps/pos/src/domain/procurement.ts::canManageProcurement) AND
	// every /procurement config route. Without it the seeded principal 403s on
	// the API and the receiving screen never renders -- which is why nothing had
	// ever demonstrated the supplier/PO pickers populating.
	//
	// procurement.approve is deliberately NOT here. A cashier does not approve
	// purchase orders, and this list is cached flat on the edge, where approval
	// must never happen at all. Criterion 5 needs a role that HOLDS approve with
	// a po_approval_limit_paise below the order total: that is the BUYER role
	// seeded below, on its own user, and never this one.
	for _, p := range []string{
		"order.create", "order.modify", "table.manage",
		"inventory.manage", "inventory.count",
		"procurement.manage",
	} {
		if _, err := pool.Exec(ctx,
			`INSERT INTO role_permission (role_id, permission) VALUES ($1, $2)
			 ON CONFLICT DO NOTHING`, roleID, p); err != nil {
			return fmt.Errorf("seeding role_permission %s: %w", p, err)
		}
	}

	// The BUYER role: raises and approves purchase orders, under a ceiling.
	// procurement.approve is what PoApprovalLimitForUser joins on, so a role
	// carrying a limit without this permission has no effect at all.
	for _, p := range []string{"procurement.manage", "procurement.approve"} {
		if _, err := pool.Exec(ctx,
			`INSERT INTO role_permission (role_id, permission) VALUES ($1, $2)
			 ON CONFLICT DO NOTHING`, buyerRoleID, p); err != nil {
			return fmt.Errorf("seeding buyer role_permission %s: %w", p, err)
		}
	}

	// The OWNER role is NAMED by the approval refusal, so it needs the
	// permission that query filters on. It also carries outlet.manage, which
	// gates POST /devices/enroll (ADR-017) -- "the closest existing permission
	// to may register hardware at this outlet", per the route's own note.
	//
	// Deliberately NOT on the cashier or the buyer. outlet.manage is the
	// permission that currently also gates the compliance config writes, so
	// whoever holds it can set the GSTIN printed on every invoice (the T7a
	// hole). A till operator and a buyer are neither technicians nor managers,
	// and widening their grant to make a fixture convenient is how a dev
	// shortcut becomes the shipped authorization model.
	//
	// menu.manage and procurement.manage were added for the M6 Phase B admin
	// console (ADR-024). Before this NO SEEDED USER HELD menu.manage AT ALL, so
	// every menu route 403'd for every dev login and the back office could not
	// be exercised end to end -- the same shape as the procurement.manage gap
	// noted above, which is why nothing had ever demonstrated the supplier
	// pickers populating.
	//
	// ON THE OWNER, NOT THE CASHIER, AND THAT IS A §50.1 BOUNDARY RATHER THAN a
	// preference. The cashier's list is cached FLAT on the edge and a config
	// pull replaces it, so anything granted there is a permission the till
	// believes it holds -- and the till must never author a menu item. Menu and
	// pricing is a management decision made in the cloud.
	for _, p := range []string{"procurement.approve", "outlet.manage", "menu.manage", "procurement.manage"} {
		if _, err := pool.Exec(ctx,
			`INSERT INTO role_permission (role_id, permission) VALUES ($1, $2)
			 ON CONFLICT DO NOTHING`, ownerRoleID, p); err != nil {
			return fmt.Errorf("seeding owner role_permission %s: %w", p, err)
		}
	}

	// The OWNER role now needs a holder after all: device enrollment is an
	// authenticated human action, and a role with no user cannot perform one.
	// It stays absent from the edge seeder -- this login exists to enroll
	// hardware and approve large orders against the cloud, never to operate a
	// till offline.
	if _, err := pool.Exec(ctx,
		`INSERT INTO app_user
		   (id, tenant_id, email, full_name, password_hash, is_active, config_version, created_at, updated_at)
		 VALUES ($1, $2, $3, 'Dev Owner', $4, TRUE, 1, $5, $5)
		 ON CONFLICT (id) DO UPDATE SET password_hash = EXCLUDED.password_hash,
		   is_active = EXCLUDED.is_active, updated_at = EXCLUDED.updated_at`,
		ownerID, tenantID, ownerEmail, passwordHash, now); err != nil {
		return fmt.Errorf("seeding owner app_user: %w", err)
	}
	if _, err := pool.Exec(ctx,
		`INSERT INTO user_role (id, user_id, role_id, outlet_id, created_at)
		 VALUES ($1, $2, $3, $4, $5)
		 ON CONFLICT (id) DO NOTHING`,
		ownerUserRoleID, ownerID, ownerRoleID, outletID, now); err != nil {
		return fmt.Errorf("seeding owner user_role: %w", err)
	}

	if _, err := pool.Exec(ctx,
		`INSERT INTO user_role (id, user_id, role_id, outlet_id, created_at)
		 VALUES ($1, $2, $3, $4, $5)
		 ON CONFLICT (id) DO NOTHING`,
		buyerUserRoleID, buyerID, buyerRoleID, outletID, now); err != nil {
		return fmt.Errorf("seeding buyer user_role: %w", err)
	}

	// The cashier's role assignment is scoped to the seeded outlet.
	if _, err := pool.Exec(ctx,
		`INSERT INTO user_role (id, user_id, role_id, outlet_id, created_at)
		 VALUES ($1, $2, $3, $4, $5)
		 ON CONFLICT (id) DO NOTHING`,
		userRoleID, cashierID, roleID, outletID, now); err != nil {
		return fmt.Errorf("seeding user_role: %w", err)
	}

	return nil
}
