//! Cross-engine parity: this crate's tax engine (`edge/database/src/tax`)
//! must reproduce `backend/internal/compliance`'s `ComputeInvoice` output
//! byte-for-byte, including `round_off_paise` and every per-line component.
//! §50.1 makes the edge authoritative for the invoice a real customer pays;
//! the cloud engine (T6) is the reference and config authority but never
//! bills anyone. If the two engines disagree by a paise, this test is the
//! one that must catch it.
//!
//! `tests/fixtures/tax_parity.json` was generated by running
//! `backend/internal/compliance`'s own `ComputeInvoice` (via a scratch Go
//! program, not committed — see the T7a report) over the case list ADR-016
//! names as mandatory: ₹x.x5 boundaries, zero and single-paise lines, many
//! small lines, cess stacked on GST, IGST-only, a fully-exempt profile, both
//! pricing modes on one invoice, and a mixed-rate bill spanning three
//! profiles.

use holler_edge_database::tax::{compute_invoice, Line, PricingMode, ResolvedRate, TaxComponent};
use serde_json::Value;

fn parse_component(s: &str) -> TaxComponent {
    match s {
        "CGST" => TaxComponent::Cgst,
        "SGST" => TaxComponent::Sgst,
        "IGST" => TaxComponent::Igst,
        "CESS" => TaxComponent::Cess,
        other => panic!("unknown tax component in fixture: {other}"),
    }
}

fn parse_pricing_mode(s: &str) -> PricingMode {
    match s {
        "INCLUSIVE" => PricingMode::Inclusive,
        "EXCLUSIVE" => PricingMode::Exclusive,
        other => panic!("unknown pricing mode in fixture: {other}"),
    }
}

fn i64_field(v: &Value, key: &str) -> i64 {
    v.get(key)
        .and_then(Value::as_i64)
        .unwrap_or_else(|| panic!("fixture: missing/invalid integer field {key:?} in {v}"))
}

fn str_field(v: &Value, key: &str) -> String {
    v.get(key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("fixture: missing/invalid string field {key:?} in {v}"))
        .to_string()
}

fn line_from_fixture(l: &Value) -> Line {
    let rates: Vec<ResolvedRate> = l["rates"]
        .as_array()
        .expect("fixture: line.rates must be an array")
        .iter()
        .map(|r| ResolvedRate {
            component: parse_component(&str_field(r, "component")),
            rate_bps: i64_field(r, "rate_bps"),
        })
        .collect();

    Line {
        order_item_id: str_field(l, "order_item_id"),
        description: str_field(l, "description"),
        hsn_sac: None,
        quantity: i64_field(l, "quantity"),
        unit_price_paise: i64_field(l, "unit_price_paise"),
        discount_per_unit_paise: i64_field(l, "discount_per_unit_paise"),
        tax_profile_id: str_field(l, "tax_profile_id"),
        pricing_mode: parse_pricing_mode(&str_field(l, "pricing_mode")),
        rates,
    }
}

#[test]
fn edge_engine_reproduces_go_engine_fixtures_exactly() {
    let raw = include_str!("fixtures/tax_parity.json");
    let root: Value = serde_json::from_str(raw).expect("fixture JSON must parse");
    let cases = root["compute_cases"]
        .as_array()
        .expect("fixture: compute_cases must be an array");
    assert!(
        !cases.is_empty(),
        "fixture must carry at least one parity case"
    );

    for case in cases {
        let name = str_field(case, "name");
        let lines: Vec<Line> = case["lines"]
            .as_array()
            .unwrap_or_else(|| panic!("case {name}: lines must be an array"))
            .iter()
            .map(line_from_fixture)
            .collect();

        let (lcs, totals) = compute_invoice(&lines)
            .unwrap_or_else(|e| panic!("case {name}: compute_invoice failed: {e}"));

        let expected_lcs = case["line_computations"]
            .as_array()
            .unwrap_or_else(|| panic!("case {name}: line_computations must be an array"));
        assert_eq!(
            lcs.len(),
            expected_lcs.len(),
            "case {name}: line count mismatch"
        );

        for (lc, expected) in lcs.iter().zip(expected_lcs.iter()) {
            let oid = &lc.order_item_id;
            assert_eq!(
                lc.gross_paise,
                i64_field(expected, "gross_paise"),
                "case {name} line {oid}: gross_paise"
            );
            assert_eq!(
                lc.discount_paise,
                i64_field(expected, "discount_paise"),
                "case {name} line {oid}: discount_paise"
            );
            assert_eq!(
                lc.taxable_value_paise,
                i64_field(expected, "taxable_value_paise"),
                "case {name} line {oid}: taxable_value_paise"
            );
            assert_eq!(
                lc.cgst_paise,
                i64_field(expected, "cgst_paise"),
                "case {name} line {oid}: cgst_paise"
            );
            assert_eq!(
                lc.sgst_paise,
                i64_field(expected, "sgst_paise"),
                "case {name} line {oid}: sgst_paise"
            );
            assert_eq!(
                lc.igst_paise,
                i64_field(expected, "igst_paise"),
                "case {name} line {oid}: igst_paise"
            );
            assert_eq!(
                lc.cess_paise,
                i64_field(expected, "cess_paise"),
                "case {name} line {oid}: cess_paise"
            );
            assert_eq!(
                lc.total_paise,
                i64_field(expected, "total_paise"),
                "case {name} line {oid}: total_paise"
            );
        }

        let expected_totals = &case["totals"];
        assert_eq!(
            totals.subtotal_paise,
            i64_field(expected_totals, "subtotal_paise"),
            "case {name}: subtotal_paise"
        );
        assert_eq!(
            totals.discount_paise,
            i64_field(expected_totals, "discount_paise"),
            "case {name}: discount_paise"
        );
        assert_eq!(
            totals.taxable_value_paise,
            i64_field(expected_totals, "taxable_value_paise"),
            "case {name}: taxable_value_paise"
        );
        assert_eq!(
            totals.cgst_paise,
            i64_field(expected_totals, "cgst_paise"),
            "case {name}: cgst_paise"
        );
        assert_eq!(
            totals.sgst_paise,
            i64_field(expected_totals, "sgst_paise"),
            "case {name}: sgst_paise"
        );
        assert_eq!(
            totals.igst_paise,
            i64_field(expected_totals, "igst_paise"),
            "case {name}: igst_paise"
        );
        assert_eq!(
            totals.cess_paise,
            i64_field(expected_totals, "cess_paise"),
            "case {name}: cess_paise"
        );
        assert_eq!(
            totals.round_off_paise,
            i64_field(expected_totals, "round_off_paise"),
            "case {name}: round_off_paise"
        );
        assert_eq!(
            totals.grand_total_paise,
            i64_field(expected_totals, "grand_total_paise"),
            "case {name}: grand_total_paise"
        );

        // Independent reconciliation check (not sourced from the fixture):
        // line-level components must sum to the invoice-level components —
        // the property T6's gate found the hard way.
        let sum_cgst: i64 = lcs.iter().map(|l| l.cgst_paise).sum();
        let sum_sgst: i64 = lcs.iter().map(|l| l.sgst_paise).sum();
        let sum_igst: i64 = lcs.iter().map(|l| l.igst_paise).sum();
        let sum_cess: i64 = lcs.iter().map(|l| l.cess_paise).sum();
        assert_eq!(
            sum_cgst, totals.cgst_paise,
            "case {name}: Σ(line.cgst_paise) != invoice.cgst_paise"
        );
        assert_eq!(
            sum_sgst, totals.sgst_paise,
            "case {name}: Σ(line.sgst_paise) != invoice.sgst_paise"
        );
        assert_eq!(
            sum_igst, totals.igst_paise,
            "case {name}: Σ(line.igst_paise) != invoice.igst_paise"
        );
        assert_eq!(
            sum_cess, totals.cess_paise,
            "case {name}: Σ(line.cess_paise) != invoice.cess_paise"
        );

        // ADR-016 §3 bound: |round_off| <= 50 paise.
        assert!(
            totals.round_off_paise >= -50 && totals.round_off_paise <= 50,
            "case {name}: round_off_paise {} exceeds the +/-50 paise bound",
            totals.round_off_paise
        );
        // ADR-016 §3: grand_total = Σ(components) + round_off.
        let pre_round = totals.taxable_value_paise
            + totals.cgst_paise
            + totals.sgst_paise
            + totals.igst_paise
            + totals.cess_paise;
        assert_eq!(
            totals.grand_total_paise,
            pre_round + totals.round_off_paise,
            "case {name}: grand_total_paise does not equal Σ(components) + round_off_paise"
        );
    }
}
